### ISSUE TITLE
Should secret.yaml be committed?

### ISSUE THREAD

**Issue by pavsaund** [dolittle-platform/Studio#13]
Should the [secret.yaml](https://github.com/dolittle-platform/Studio/blob/master/K8s/secret.yml)-file be committed to the repository?

**Comment by einari** [comment]
Kool.. :).   No, it should not - in fact the whole file does not need to be anywhere as it is holding the TLS certificate, which is managed by Traefik anyways.. Deleted it shall be.

**Comment by einari** [comment]
Deleted
